#' Sidekick Calibration Data
#'
#' An example of the sidekick calibration in the Meadows V2 field site.
#'
#' @format ## `sidekick_cal`
#' A data frame with 716 rows and 8 columns:
#' \describe{
#'   \item{tag_type}{Tag type detected}
#'   \item{tag_id}{Tag ID}
#'   \item{time_utc}{Time in UTC}
#'   \item{rssi}{Received signal strength indicator in dBm}
#'   \item{lat}{Latitude}
#'   \item{lon}{Longitude}
#'   \item{heading}{Cardinal direction}
#'   \item{antenna_angle}{Angle of antenna}
#' }
#'
#' @source {sidekick} file generated by sidekick
"sidekick_cal"
